# Generated by Django 5.2.3 on 2025-06-22 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('class_names', models.JSONField()),
                ('train_ratio', models.FloatField(default=0.8)),
                ('image_size', models.IntegerField(default=640)),
                ('epochs', models.IntegerField(default=100)),
                ('batch_size', models.IntegerField(default=16)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('training', 'Training'), ('done', 'Done'), ('error', 'Error')], default='idle', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnchorSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p3', models.JSONField()),
                ('p4', models.JSONField()),
                ('p5', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anchor_set', to='trainer.project')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mAP50', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('loss_box', models.FloatField(blank=True, null=True)),
                ('loss_obj', models.FloatField(blank=True, null=True)),
                ('loss_cls', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_results', to='trainer.project')),
            ],
        ),
    ]
