# Generated by Django 5.2.3 on 2025-06-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='class_names',
            field=models.TextField(help_text='Satır satır her class ismi'),
        ),
    ]
