# Generated by Django 5.2.3 on 2025-06-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_alter_project_class_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='batch_size',
        ),
        migrations.RemoveField(
            model_name='project',
            name='epochs',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image_size',
        ),
        migrations.AddField(
            model_name='project',
            name='process_name',
            field=models.CharField(default='Unnamed Process', max_length=255),
        ),
        migrations.AddField(
            model_name='trainingresult',
            name='batch_size',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='trainingresult',
            name='device',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='trainingresult',
            name='epochs',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='trainingresult',
            name='extra_args',
            field=models.TextField(blank=True, help_text='Opsiyonel flagler. Örn: "--noautoanchor --exist-ok"'),
        ),
        migrations.AddField(
            model_name='trainingresult',
            name='hyp_path',
            field=models.CharField(default='yolov7/data/hyp.scratch.custom.yaml', max_length=255),
        ),
        migrations.AddField(
            model_name='trainingresult',
            name='image_size',
            field=models.IntegerField(default=640),
        ),
        migrations.AddField(
            model_name='trainingresult',
            name='weights_path',
            field=models.CharField(default='yolov7/yolov7.pt', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='Idle', max_length=50),
        ),
    ]
