# Generated by Django 5.2.3 on 2025-06-22 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_remove_project_batch_size_remove_project_epochs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_size', models.IntegerField(default=640)),
                ('epochs', models.IntegerField(default=100)),
                ('batch_size', models.IntegerField(default=16)),
                ('weights_path', models.CharField(default='yolov7/yolov7.pt', max_length=255)),
                ('device', models.CharField(default='0', max_length=10)),
                ('hyp_path', models.CharField(default='yolov7/data/hyp.scratch.custom.yaml', max_length=255)),
                ('noautoanchor', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('anchors_p3', models.JSONField(blank=True, null=True)),
                ('anchors_p4', models.JSONField(blank=True, null=True)),
                ('anchors_p5', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(limit_choices_to={'status': 'done'}, on_delete=django.db.models.deletion.CASCADE, to='trainer.project')),
            ],
        ),
        migrations.DeleteModel(
            name='AnchorSet',
        ),
    ]
