# Generated by Django 5.2.3 on 2025-06-22 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_training_delete_anchorset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='description',
        ),
        migrations.RemoveField(
            model_name='training',
            name='image_size',
        ),
        migrations.AddField(
            model_name='project',
            name='batch_size',
            field=models.PositiveIntegerField(default=16),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='epochs',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='project',
            name='img_size',
            field=models.PositiveIntegerField(default=640),
        ),
        migrations.AddField(
            model_name='project',
            name='noautoanchor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='training',
            name='extra_args',
            field=models.TextField(blank=True, help_text='Örn: "--noautoanchor --exist-ok"'),
        ),
        migrations.AddField(
            model_name='training',
            name='img_size',
            field=models.PositiveIntegerField(default=640),
        ),
        migrations.AlterField(
            model_name='project',
            name='class_names',
            field=models.TextField(help_text='Her satır bir class ismi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='anchors_p3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='anchors_p4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='anchors_p5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='batch_size',
            field=models.PositiveIntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='training',
            name='epochs',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='training',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='trainer.project'),
        ),
        migrations.AlterField(
            model_name='trainingresult',
            name='extra_args',
            field=models.TextField(blank=True),
        ),
    ]
