# Generated by Django 5.2.3 on 2025-06-22 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_remove_training_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='class_names',
            field=models.JSONField(default=list, help_text='Sınıf isimleri (JSON listesi)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Idle', 'Idle'), ('done', 'Done'), ('error', 'Error')], default='Idle', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='train_ratio',
            field=models.FloatField(default=0.8, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
