# Generated by Django 5.2.3 on 2025-06-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_alter_project_class_names_alter_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='idle', max_length=20),
        ),
    ]
