# Generated by Django 5.2.3 on 2025-06-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0007_alter_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='batch_size',
        ),
        migrations.RemoveField(
            model_name='project',
            name='epochs',
        ),
        migrations.RemoveField(
            model_name='project',
            name='img_size',
        ),
        migrations.RemoveField(
            model_name='project',
            name='noautoanchor',
        ),
    ]
