# Generated by Django 5.2.3 on 2025-06-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0008_remove_project_batch_size_remove_project_epochs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='anchors_p3',
        ),
        migrations.RemoveField(
            model_name='training',
            name='anchors_p4',
        ),
        migrations.RemoveField(
            model_name='training',
            name='anchors_p5',
        ),
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='class_names',
            field=models.TextField(help_text='Her satıra bir sınıf ismi yazın.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Idle', 'Idle'), ('done', 'Done'), ('error', 'Error'), ('missing', 'Missing')], default='idle', max_length=20),
        ),
    ]
