# Generated by Django 5.2.3 on 2025-06-23 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0009_remove_training_anchors_p3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='description',
        ),
    ]
