# Generated by Django 5.2.3 on 2025-06-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0010_remove_training_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
