# Generated by Django 5.2.3 on 2025-06-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0011_training_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='anchor_report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
