# Generated by Django 5.2.3 on 2025-06-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0012_training_anchor_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('error', 'Error'), ('started', 'Started')], default='started', max_length=50),
        ),
    ]
