# Generated by Django 5.2.3 on 2025-06-26 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0013_alter_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingresult',
            name='batch_size',
        ),
        migrations.RemoveField(
            model_name='trainingresult',
            name='device',
        ),
        migrations.RemoveField(
            model_name='trainingresult',
            name='epochs',
        ),
        migrations.RemoveField(
            model_name='trainingresult',
            name='extra_args',
        ),
        migrations.RemoveField(
            model_name='trainingresult',
            name='hyp_path',
        ),
        migrations.RemoveField(
            model_name='trainingresult',
            name='image_size',
        ),
        migrations.RemoveField(
            model_name='trainingresult',
            name='project',
        ),
        migrations.RemoveField(
            model_name='trainingresult',
            name='weights_path',
        ),
        migrations.AddField(
            model_name='training',
            name='current_epoch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='duration_min',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='log_file_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='output_dir',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='progress_percent',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('done', 'Done'), ('error', 'Error'), ('queued', 'Queued')], default='queued', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingresult',
            name='empty_image_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingresult',
            name='gflops',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trainingresult',
            name='gpu_memory_usage',
            field=models.CharField(default='0G', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingresult',
            name='image_count_train',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingresult',
            name='image_count_val',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingresult',
            name='layer_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingresult',
            name='num_workers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingresult',
            name='parameter_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingresult',
            name='training',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='trainer.training'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingresult',
            name='weight_transfer_info',
            field=models.CharField(default='0/0', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Idle', 'Idle'), ('started', 'Started'), ('done', 'Done'), ('error', 'Error'), ('missing', 'Missing')], default='Idle', max_length=50),
        ),
        migrations.AlterField(
            model_name='training',
            name='extra_args',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TensorboardResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_box_loss', models.FloatField()),
                ('train_obj_loss', models.FloatField()),
                ('train_cls_loss', models.FloatField()),
                ('val_box_loss', models.FloatField()),
                ('val_obj_loss', models.FloatField()),
                ('val_cls_loss', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('map_0_5', models.FloatField()),
                ('map_0_5_0_95', models.FloatField()),
                ('lr0', models.FloatField()),
                ('lr2', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tensorboard_entries', to='trainer.training')),
                ('training_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tensorboard', to='trainer.trainingresult')),
            ],
        ),
    ]
