# Generated by Django 5.2.3 on 2025-06-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0014_remove_trainingresult_batch_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='anchors_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
