# Generated by Django 5.2.3 on 2025-06-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0015_training_anchors_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tensorboardresult',
            name='lr0',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='tensorboardresult',
            name='lr2',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='tensorboardresult',
            name='map_0_5',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='tensorboardresult',
            name='map_0_5_0_95',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='tensorboardresult',
            name='precision',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='tensorboardresult',
            name='recall',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='tensorboardresult',
            name='train_box_loss',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='tensorboardresult',
            name='train_cls_loss',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='tensorboardresult',
            name='train_obj_loss',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='tensorboardresult',
            name='val_box_loss',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='tensorboardresult',
            name='val_cls_loss',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='tensorboardresult',
            name='val_obj_loss',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
