# Generated by Django 5.2.3 on 2025-06-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0016_alter_tensorboardresult_lr0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='gpu_memory_usage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trainingresult',
            name='custom_best_model_epoch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingresult',
            name='custom_best_model_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
