# Generated by Django 5.2.3 on 2025-06-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0017_training_gpu_memory_usage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='gpu_memory_usage',
        ),
        migrations.AddField(
            model_name='trainingresult',
            name='mAP50_95',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
